App.Web/Controllers/AccountingController.cs
using DataTransferObject.DTOClasses;
using Mapster;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Service.ServiceInterfaces;

namespace App.Web.Controllers;

public class AccountingController : Controller
{
    private readonly IUserService _userService;

    public AccountingController(IUserService userService)
    {
        _userService = userService;
    }

    [HttpGet]
    public IActionResult Login()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> LoginPostAsync(LoginDTO login)
    {
        if (ModelState.IsValid)
        {
            var result = await _userService.LoginAsync(login);
            if (result)
            {
                TempData["SuccessMessage"] = "Logged in Successfully";
                return LocalRedirect("/Home/Index");
            }                    
        }
        ViewData["ErrorMessage"] = "Login Failed";
        return View("Login");
    }

    [HttpGet]
    public IActionResult Register() 
    {
        return View();
    }
    [HttpPost]
    public async Task<IActionResult> RegisterPostAsync(UserDTO user)
    {
        if(ModelState.IsValid)
        {
            try
            {                    
                var result = await _userService.RegisterAsync(user);
                TempData["SuccessMessage"] = "Registration Successful";

                return LocalRedirect("/Home/Index");
            } 
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = ex.Message;
            }
        }
        return View("Register");
    }
    [Authorize]
    [HttpGet]
    public async Task<IActionResult> Logout()
    {
        var userName = User.Identity?.Name;
        if (!string.IsNullOrWhiteSpace(userName))
        {
            try
            {
                await _userService.LogoutAsync(userName);
                TempData["SuccessMessage"] = "Logout Successfully.";
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = ex.Message;
            }
        }
        
        return LocalRedirect("/Home/Index");
    }
    [Authorize]
    [HttpGet]
    public async Task<ActionResult<EditProfileDTO>> EditProfile()
    {
        var user = await _userService.GetUser(User.Identity?.Name ?? "");
        var res = new EditProfileDTO();
        if (user != null)
        {
            res = user.Adapt<EditProfileDTO>();
        }
        return View(res);
    }
    [Authorize]
    [HttpPost]
    public async Task<IActionResult> EditProfileAsync(EditProfileDTO profile)
    {
        if (ModelState.IsValid)
        {            
            try
            {
                await _userService.UpdateAsync(profile, User.Identity?.Name ?? "");
                TempData["SuccessMessage"] = "User update completed";
                return RedirectToAction("Index", "Home");
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = ex.Message;
            }
        }

        return View("EditProfile", profile);
    }
}

App.Web/Controllers/DepartementController.cs
using DataTransferObject.DTOClasses;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Service.ServicClasses;
using Service.ServiceInterfaces;
using Shared;
using System.Security.Claims;

namespace App.Web.Controllers;
[Authorize (Roles ="Admin")]
public class DepartementController : Controller
{
    private readonly IDepartementService _departementService;

    public DepartementController(IDepartementService departementService)
    {
        _departementService = departementService;
    }
    [HttpGet]
    public async Task<IActionResult> GetAll(int? pageindex, string searchName)
    {
        var data =  await _departementService.GetDepartementListAsPagination(3, pageindex.HasValue ? pageindex.Value : 1, searchName);
        return View(data);
        
    }
    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }
    [HttpPost]
    public async Task<IActionResult> CreateAsync(DepartementDTO departement)
    {
        if(ModelState.IsValid)
        {
            try
            {
                await _departementService.AddDepartement(departement);
                TempData["SuccessMessage"] = "CreateNewDepartement Successful";
                return LocalRedirect("/Departement/GetAll");
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = ex.Message;
            }
        }
        return View(nameof(Create));
    }
    [HttpGet]
    public async Task<IActionResult> Edit(Guid id)
    {
        var departement =  await _departementService.GetDepartement(id.ToString());

        return View(departement);
    }
    [HttpPost]
    public async Task<IActionResult> EditAsync(DepartementDTO departement)
    {
        if(ModelState.IsValid)
        {
            try
            {
                await _departementService.UpdateDepartement(departement,new Guid(User.FindFirstValue(ClaimTypes.NameIdentifier) ?? Guid.Empty.ToString()));
                TempData["SuccessMessage"] = "UpdateDepartement Successful";
                return LocalRedirect("/Departement/GetAll");
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = ex.Message;
            }
        }
        return LocalRedirect("/Departement/GetAll");
    }    
    [HttpGet]
    public async Task<IActionResult> Delete(Guid id)
    {
        try
        {
            await _departementService.DeleteDepartement(id, new Guid(User.FindFirstValue(ClaimTypes.NameIdentifier) ?? Guid.Empty.ToString()));
            TempData["SuccessMessage"] = "DeleteDepartement Successful";
            return LocalRedirect("/Departement/GetAll");
        }
        catch (Exception ex)
        {
            ViewData["ErrorMessage"] = ex.Message;
        }
        return LocalRedirect("/Departement/GetAll");
    }
}

App.Web/Views/Shared/_Layout.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    @*<meta name="viewport" content="width=device-width, initial-scale=1.0" />*@
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
    <link href="~/css/stylesTemp.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Styles", required: false)
</head>

<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" asp-controller="Home" asp-action="Index">CRM</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            @* <div class="input-group">
            <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
            <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
            </div> *@
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
            @if (!User.Identity?.IsAuthenticated ?? true)
            {
                <a class="btn btn-success nav-item" asp-controller="Accounting" asp-action="Login">LogIn</a>
            }
            else
            {
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" asp-controller="Accounting" asp-action="EditProfile">Edit Profile</a></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li>
                            <a class="dropdown-item" asp-controller="Accounting" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                </li>
            }
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading"></div> @* Interface *@
                        @if (User.Identity?.IsAuthenticated ?? true)
                        {
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                                Ticket
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" asp-controller="Ticket" asp-action="Create">New Ticket</a>
                                    <a class="nav-link" asp-controller="Ticket" asp-action="GetAllByUserId">All Ticket</a>
                                    @if (User.IsInRole("Admin"))
                                    {
                                        <a class="nav-link" asp-controller="Ticket" asp-action="GetAll">All TicketAdmin</a>
                                    }
                                </nav>
                            </div>
                        }
                        @if (User.IsInRole("Admin"))
                        {

                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseCategory" aria-expanded="false" aria-controls="collapseCategory">
                                Category
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseCategory" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" asp-controller="Category" asp-action="CreateCategory">New Category</a>
                                    <a class="nav-link" asp-controller="Category" asp-action="index">All Category</a>
                                </nav>
                            </div>
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseDepartement" aria-expanded="false" aria-controls="collapseDepartement">
                                Departement
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseDepartement" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" asp-controller="Departement" asp-action="Create">New Departement</a>
                                    <a class="nav-link" asp-controller="Departement" asp-action="GetAll">All Departement</a>
                                </nav>
                            </div>
                        }
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Start Bootstrap
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                @RenderBody()
            </main>
        </div>
    </div>
    @if (!string.IsNullOrWhiteSpace(ViewData["ErrorMessage"]?.ToString()))
    {
        <div class="position-fixed bottom-0 end-0 p-3" style="z-index: 11">
            <div id="error-toast" class="toast align-items-center text-white bg-danger border-0" role="alert" aria-live="assertive" aria-atomic="true">
                <div class="d-flex">
                    <div id="error-toast-body" class="toast-body">
                        @(ViewData["ErrorMessage"]?.ToString() ?? "Something went wrong.")
                    </div>
                    <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
            </div>
        </div>
    }
    @if (!string.IsNullOrWhiteSpace(TempData["SuccessMessage"]?.ToString()))
    {
        <div class="position-fixed bottom-0 end-0 p-3" style="z-index: 11">
            <div id="success-toast" class="toast align-items-center text-white bg-success border-0" role="alert" aria-live="assertive" aria-atomic="true">
                <div class="d-flex">
                    <div id="error-toast-body" class="toast-body">
                        @(TempData["SuccessMessage"]?.ToString() ?? "Your request processed successfully.")
                    </div>
                    <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
            </div>
        </div>
    }

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/js/scriptsTemp.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>
    <script src="~/js/datatables-simple-demo.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>